language: ruby

rvm:
- 2.1

install:
  - bundle install
  - gem install jekyll
script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - tar -czvf site.tgz _site/*
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST
  - tar --script-components 1 -xzvf site.tgz
  - rm site.tgz
