language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - nvm install 5.4.1
  - npm install
  - gem install jekyll

script:
  - gulp
  - bundle exec jekyll build

branches:
  only:
  - master

after_success:
  - tar -czvf chrisburnell.tgz _site/*
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -P $DEPLOY_PORT -o stricthostkeychecking=no chrisburnell.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
