language: ruby
rvm:
- 2.1

install:
  - bundle install
  - gem install jekyll
script: jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  "curl --ftp-create-dirs -T _site -u $FTP_USERNAME:$FTP_PASSWORD ftp://ftp.chrisburnell.com/sites/sitetestamazing/"
