language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - gem install jekyll

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - tar -czvf site.tgz _site/*
  - export SSHPASS=$DEPLOY_PASSWORD
  - curl --ftp-create-dirs -T site.tgz -u $DEPLOY_USERNAME:$DEPLOY_PASSWORD ftp://$DEPLOY_HOST/$DEPLOY_REMOTEDIR/site.tgz
  - ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST
  - yes
  - $DEPLOY_PASSWORD
  - ls -a
  - cd sites
  - cd sitetestamazing
  - tar --strip-components 1 -xzvf site.tgz
  - rm site.tgz
