language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - gem install jekyll

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - export SSHPASS=$DEPLOY_PASSWORD
  - tar -czvf site.tgz _site/*
  - sshpass -e sftp -oPort=$DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST:/$DEPLOY_REMOTEDIR/
  - put site.tgz
  - tar --strip-components 1 -xzvf site.tgz
  - rm site.tgz
