language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - gem install jekyll

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - tar -czvf chrisburnell.tgz
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -P $DEPLOY_PORT chrisburnell.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH/chrisburnell.tgz
  - sshpass -e ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
