language: ruby
rvm:
- 2.1

install:
  - bundle install
  - gem install jekyll
script: jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - tar -czf site.tgz _site/*
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp site.tgz $DEPLOY_USERNAME@$DEPLOY_HOST
  - sshpass -e scp ssh $DEPLOY_USERNAME@$DEPLOY_HOST
  - tar -xzf site.tgz
  - rm site.tgz
