language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - gem install jekyll

before_script:
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - export SSHPASS=$DEPLOY_PASSWORD
  - tar -czvf site.tgz _site/*
  - sshpass -e scp -P $DEPLOY_PORT site.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_REMOTEDIR/site.tgz
  - sshpass -e ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST $DEPLOY_REMOTEDIR/deploy.sh
