language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
      - sshpass

install:
  - bundle install
  - gem install jekyll
script:
  - jekyll build

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

after_success:
  - bundle exec travis-custom-deploy sftp service:jekyll
