title: Chris Burnell
description: "I’m a Canadian user interface developer living in London, UK. This is where I write about and share my passion: CSS architecture, design, innovations, standards, and user experience."
tagline: "I’m ravenous for CSS"
author: Chris Burnell
url: http://chrisburnell.com
email: me@chrisburnell.com
twitter_user: iamchrisburnell

employer: Squiz UK
employer_url: http://squiz.net

twitter_url: http://twitter.com/iamchrisburnell
codepen_url: http://codepen.io/chrisburnell
lastfm_url: http://last.fm/user/chrisburnell

timezone: Europe/London
destination: ./_site
layouts: ./_layouts

future: false
permalink: /articles/:title
paginate: 10
paginate_path: 'page:num'

markdown: rdiscount
rdiscount:
  extensions: [smart]
markdown_ext: markdown,mkd,mkdn,md
