title:       Chris Burnell
description: "I’m a Canadian UI Developer living in London, UK. This is where I write about and share my passions: CSS, front-end architecture, web standards, innovation, and user experience."
tagline:     "I’m ravenous for CSS"

author:         Chris Burnell
author_age:     25
author_email:   me@chrisburnell.com
author_twitter: iamchrisburnell

job_title:    UI developer
employer:     City University
employer_url: https://www.city.ac.uk

shorturl:    http://repc.co/

codepen_url: http://codepen.io/chrisburnell
github_url:  https://github.com/chrisburnell
lastfm_url:  http://last.fm/user/chrisburnell
twitter_url: https://twitter.com/iamchrisburnell

codepen_theme:   119
codepen_tabfree: 8863

timezone: Europe/London
destination: ./_site
layouts: ./_layouts
permalink: /article/:title
collections:
  pens:
    output: true
    permalink: /pen/:title
paginate: 9001
paginate_path: 'page:num'
exclude: ['node_modules, .sass-cache']

markdown: rdiscount
rdiscount:
  extensions: [smart]
markdown_ext: markdown,mkd,mkdn,md

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
