title:       Chris Burnell
short_title: cb
tagline:     'I’m Ravenous for CSS.'
lede:        'I’m a <span class="canada">Canadian</span> UI developer living in London, UK. This is where I write about and share my passions: CSS, best practices and web standards, performance, front-end architecture, and innovations on the web.'
version:     3.1.0
color:       5f8aa6

author:
  name:        Chris Burnell
  nationality: Canadian
  location:    London, UK
  email:       me@chrisburnell.com
  job_title:   UI developer
  codepen:     chrisburnell
  twitter:     '@iamchrisburnell'
  employer:
    name: City, University of London
    url:  https://www.city.ac.uk

url:      https://chrisburnell.com
baseurl:  ''
shorturl: https://repc.co/

urls:
  codepen:      https://codepen.io/chrisburnell
  gist:         https://gist.github.com/chrisburnell
  github:       https://github.com/chrisburnell
  github_repo:  https://github.com/chrisburnell/chrisburnell.com
  lastfm:       https://last.fm/user/chrisburnell
  license:      https://www.gnu.org/licenses/gpl-3.0.txt
  ravenous:     https://ravenous.chrisburnell.com
  rss:          /feed.xml
  rss_articles: /feed-articles.xml
  rss_links:    /feed-links.xml
  rss_pens:     /feed-pens.xml
  rss_talks:    /feed-talks.xml
  sassdoc:      /sassdoc
  speakerdeck:  https://speakerdeck.com/chrisburnell
  spotify:      https://open.spotify.com/user/1128245857
  twitter:      https://twitter.com/iamchrisburnell

sitemap:
  changefreq: monthly
  priority:   0.5

codepen:
  page: details
  themes:
    default: 119
    tabfree: 8863

timezone: Europe/London
language: en

future: true
incremental: true
destination: ./_site
layouts_dir: ./_layouts
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      path: '_drafts'
    values:
      layout: 'draft'
  -
    scope:
      path: '_posts'
    values:
      layout: 'post'
      comments: true
      webmentions: true

exclude:
- CNAME
- CONTRIBUTING.md
- deploy.sh
- Gemfile
- Gemfile.lock
- gulpfile.babel.js
- LICENSE
- node_modules
- package.json
- README.md
- src
- vendor
- yarn.lock

gems:
- jekyll-redirect-from
- jemoji
