title:       Chris Burnell
lede:        "I’m a Canadian UI developer living in London, UK. This is where I write about and share my passions: CSS, best practices and web standards, performance, front-end architecture, and innovations on the web."
tagline:     "I’m ravenous for CSS"
brand_color: 5f8aa6

author:           Chris Burnell
author_age:       25
author_location:  London, UK
author_email:     me@chrisburnell.com
author_twitter:   iamchrisburnell
author_job_title: UI developer

employer:     City University
employer_url: https://www.city.ac.uk

url:      https://chrisburnell.com
baseurl:  ""
shorturl: http://repc.co/

url_repository: https://github.com/chrisburnell/chrisburnell.github.io
url_ravenous:   https://ravenous.chrisburnell.com

url_codepen: http://codepen.io/chrisburnell
url_github:  https://github.com/chrisburnell
url_gist:    https://gist.github.com/chrisburnell
url_lastfm:  http://last.fm/user/chrisburnell
url_twitter: https://twitter.com/iamchrisburnell

copyright:     Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported
url_copyright: http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

codepen_theme:   119
codepen_tabfree: 8863

timezone: Europe/London

destination: ./_site
layouts: ./_layouts
permalink: /:categories/:title/
exclude: ['node_modules', '.sass-cache']

gems:
- jekyll-redirect-from
- jekyll-sitemap
- jemoji
