title:       Chris Burnell
tagline:     "I’m ravenous for CSS."
lede:        "I’m a Canadian UI developer living in London, UK. This is where I write about and share my passions: CSS, best practices and web standards, performance, front-end architecture, and innovations on the web."
color_brand: 5f8aa6

author:
  name:      Chris Burnell
  age:       25
  location:  London, UK
  email:     me@chrisburnell.com
  codepen:   chrisburnell
  twitter:   iamchrisburnell
  job_title: UI developer
  employer:
    name: City University
    url:  https://www.city.ac.uk

url:      https://chrisburnell.com
baseurl:  ""
shorturl: http://repc.co/

urls:
  ravenous: https://ravenous.chrisburnell.com
  codepen:  http://codepen.io/chrisburnell
  gist:     https://gist.github.com/chrisburnell
  lastfm:   http://last.fm/user/chrisburnell
  twitter:  https://twitter.com/iamchrisburnell

copyright:
  name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 Unported
  url:  http://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

sitemap:
  changefreq: monthly
  priority:   0.5

codepen:
  page: details
  themes:
    default: 119
    tabfree: 8863

timezone: Europe/London

incremental: true
destination: ./_site
layouts_dir: ./_layouts
permalink: /:categories/:title/

exclude:
- .DS_Store
- .sass-cache
- .travis.yml
- CNAME
- CONTRIBUTING.md
- deploy.sh
- Gemfile
- gulpfile.js
- package.json
- node_modules
- README.md
- src

gems:
- jekyll-redirect-from
# - jemoji
